using LightXML	

options_location = ARGS[1]
output_location = ARGS[2]

println(options_location)
println(output_location)

xdoc = parse_file(ascii(options_location))

warning = """# DO NOT EDIT THIS FILE BY HAND. This file was generated using
# parse_fdb_options.jl, part of the FoundationDB.jl repository, and a copy of the
# fdb.options file (installed as part of the FoundationDB client, typically
# found as /usr/include/foundationdb/fdb.options).

# To regenerate this file, from the top level of a FoundationDB.jl repository checkout,
# run:
# \$ julia _utils/parse_fdb_options.jl /usr/include/foundationdb/fdb.options src/generated.jl
"""

out_file = open(output_location, "w+")

write(out_file, warning)
close(out_file)
